import os

from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer
)

from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.pagesizes import letter


def generate_pdf_report(name, company, analysis):
    
    os.makedirs("generated_reports", exist_ok=True)

    output_path = f"generated_reports/{company}.pdf"

    doc = SimpleDocTemplate(
        output_path,
        pagesize=letter
    )

    styles = getSampleStyleSheet()

    elements = []

    # TITLE
    title = Paragraph(
        f"<font size='24'><b>{company}</b></font>",
        styles["Title"]
    )

    elements.append(title)

    elements.append(Spacer(1, 20))

    # SUBTITLE
    subtitle = Paragraph(
        "AI-Powered Business Audit Report",
        styles["Heading2"]
    )

    elements.append(subtitle)

    elements.append(Spacer(1, 30))

    # CLIENT NAME
    client = Paragraph(
        f"<b>Prepared For:</b> {name}",
        styles["Normal"]
    )

    elements.append(client)

    elements.append(Spacer(1, 30))

    # ANALYSIS
    analysis_paragraph = Paragraph(
        analysis.replace("\n", "<br/>"),
        styles["BodyText"]
    )

    elements.append(analysis_paragraph)

    elements.append(Spacer(1, 40))

    # FOOTER
    footer = Paragraph(
        "Generated by SimplifIQ AI Automation System",
        styles["Italic"]
    )

    elements.append(footer)

    # BUILD PDF
    doc.build(elements)

    return output_path